# Generated by Django 5.1.5 on 2025-01-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='classe_teste',
        ),
    ]
